### ISSUE TITLE
manifest.json error

### ISSUE THREAD

**Issue by djashjones** [asantaga/wiserHomeAssistantPlatform#104]
Just updated to R2.3 slight bug:

{
    "domain": "wiser",
    "name": "Wiser Heating Component for Home Assistant",
    "config_flow": true,
    "documentation": "https://github.com/asantaga/wiserHomeAssistantPlatform/blob/master/Readme.Md",
    "dependencies": [],
    "codeowners": ["@asantaga"],
    "requirements": ["wiser-heating-api>=1.0.7.2"],
    "zeroconf": ["_http._tcp.local."],
}

I take it the comma at the end zeroconf should not be there?

**Comment by djashjones** [comment]
Nope maybe not. The error message is:

Could not read manifest.json [Expecting property name enclosed in double quotes: line 10 column 1 (char 357)]

**Comment by msp1974** [comment]
I think it is the comma at the end but this is HACS reading it from github and not your local installed copy.  Needs the repo updating to correct.

**Comment by julezman** [comment]
Same issue here.

**Comment by scooper1** [comment]
i think this is extra comma is really playing bad tricks on HACS 
to the extent it takes a restore of a backup to get HACS to load

**Comment by scooper1** [comment]
updating to 109.4  wipes out the wiserheatingapi
then you get a wiser load failure notification 
so you reload via hacs the wiser integration  which then fails silently to install the missing wiserheatingapi
next time hassio is restarted the wiserheatingapi fails to load because its missing  
hacs load routine then fails to run - taking out a lot of others 
you restore the system from a snapshot  - which does not seam to backup the  wiserheatingapi  
which then gives you a wiser load error as above -    

the way out of this  was to

was do a restore to 109.2  (.3 may have been ok )
use portianer to start up a bash prompt in the homeassistant container 
then do 
sudo pip3 install wiser-heating-api    (or something similar)
restart the container 
upgrade to 109.4

repeat the api install

use portianer to start up a bash prompt in the homeassistant container 
then do 
sudo pip3 install wiser-heating-api    (or something similar)

hopefully you have a running system again

**Comment by DrJohnT** [comment]
Yes, same issue here.  Running HA 0.109.4
``Could not read manifest.json [Expecting property name enclosed in double quotes: line 10 column 1 (char 357)]``

I simply downgraded to Wiser integration to v2.2 and everything is fine

**Comment by thecem** [comment]
If you go back to R2..2 restart HA and update to 2.3 and restart.
Wiser is working again.

**Comment by asantaga** [comment]
Sorry I didnt see the issue until this morning (just pay more attention). Ive removed the offending comma and released 2.3.1

NO Idea how the additional comma ended up there, I don't remember editing the file.. Im guessing it ocured when modifying files with black....

please test and let me know

**Comment by thecem** [comment]
2.3.1 is working

**Comment by asantaga** [comment]
perfect... Weird thing was/is that it works perfectly fine on my HA with and without the extra comma..  very weird.

thanks for testing.. 
Closing this issue for now
