### ISSUE TITLE
When heating set to off target is null 

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#111]
from #102  @scooper1

> minor comment on the new beta
> when heating is set to off the target seems to be changed to null instead of last value
> for most displays, this would be better to just so the last or a dummy value (dummy value could be the frost protection level)

Could be done

**Comment by msp1974** [comment]
You cannot really set it to last value because if you restart HA, there is no last value, so what do you show when it is off.  The hub reports it as -20C, which is why we thought it was best to show as null ie no target temp set.  Agree not perfect but climate card cannot support any non numeric values here.
