### ISSUE TITLE
Unavailable entities and errors in log

### ISSUE THREAD

**Issue by squireblackdens** [asantaga/wiserHomeAssistantPlatform#119]
Hi

My integration, which has worked for months fine, suddenly is showing several entities and unavailable - mainly the heat hub itself, the cloud sensor and all the TRV battery levels. Connection to heat hub is fine - on HA I can see temps on rads / set temps / boost etc... all works fine.
 Running latest version of integration. Tried 2.4b but still there. Tried rolling back a few versions, still same problem.

I'm on Home Assistant 0.116.4

Noticed this error in my logs:

Logger: homeassistant.components.sensor
Source: custom_components/wiser/sensor.py:317
Integration: Sensor (documentation, issues)
First occurred: 23:04:20 (1 occurrences)
Last logged: 23:04:20

Error while setting up wiser platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/wiser/sensor.py", line 34, in async_setup_entry
    WiserDeviceSensor(data, device.get("id"), device.get("ProductType"))
  File "/config/custom_components/wiser/sensor.py", line 253, in __init__
    self._device_name = self.get_device_name()
  File "/config/custom_components/wiser/sensor.py", line 317, in get_device_name
    + self.data.wiserhub.getDeviceRoom(self._device_id)["roomName"]
  File "/usr/local/lib/python3.8/site-packages/wiserHeatingAPI/wiserHub.py", line 352, in getDeviceRoom
    return self.device2roomMap[deviceId]
KeyError: 1

**Comment by squireblackdens** [comment]
More info: all entities in domain Climate working fine. It's just entities in the sensor domain which are unavailable. Also, I'm pretty sure this error and missing sensors started just after I added some new TRVs and rooms in the Wiser app to my system. All new TRVs show up in HA but not sensors (and not sensors for devices which were previously in the system). Hope that helps!

**Comment by sappsys** [comment]
Although your integration may have been working for months, 0116.4 hasn’t been out for months. Are you sure it didn’t start when you upgraded ?

**Comment by msp1974** [comment]
Im running 0116.4 and no errors, so this is likely an issue of some sort with your hub or the new rooms you have created that the api is not handling well.Can you please provide the version of firmware on your hub and also turn on debugging for this integration and provide a log output.  The issue is happening before the actual error you are seeing and a debug log will show this better.Sent from Samsung tablet.
-------- Original message --------From: Andrew Johnson <notifications@github.com> Date: 18/10/2020  05:05  (GMT+00:00) To: asantaga/wiserHomeAssistantPlatform <wiserHomeAssistantPlatform@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [asantaga/wiserHomeAssistantPlatform] Unavailable entities and errors in log (#119) 

Although your integration may have been working for months, 0116.4 hasn’t been out for months. Are you sure it didn’t start when you upgraded ?

**Comment by scooper1** [comment]
Normally a restart of hub   wait for green led then restart hassio  fixes problemOn 18 Oct 2020 05:05, Andrew Johnson <notifications@github.com> wrote:

Although your integration may have been working for months, 0116.4 hasn’t been out for months. Are you sure it didn’t start when you upgraded ?

**Comment by asantaga** [comment]
Hey ,

Sorry for the radio silence, we just (15days ago) had our second child and things are a little busy :-) 

That said I was looking at the project and trying to work out what to do with it.. 

Ive just upgraded my HA from (very old) to latest HA ( 0.116.4) and restarted and all is still working well..

I wonder if it is a different, more networking error? 
The app on my phone is saying 3.11.0, I will check the hub later

**Comment by squireblackdens** [comment]
Hi. I looked at the rooms I had added on the Wiser app and realised that one of them had a number character at the end, which none of the others had. So I changed that and power cycled the Wiser Hub. All seems to be working now. Thanks
