### ISSUE TITLE
Error display : 

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#195]
Hello the community,
I'm trying this new V3 release
when displaying the energy consumption _Total_Power, apply a dividing coefficient of 1000 to have the data in kW/h, else the data is in W/h. 

To fix it, in the sensor.py file , in class WiserSmartplugPower(WiserSensor):
   if self._sensor_type == "Power":
            self._state = self._device.instantaneous_power
        else:
            self._state = self._device.delivered_power **/ 1000**

       
![image](https://user-images.githubusercontent.com/95585425/147278395-746f5fe4-d9f1-4d33-bb57-156948ee166d.png)

**Comment by msp1974** [comment]
Thanks @LGO44. There was a couple of issues with this power sensor which have been fixed in an update published today.  The one you have  noted above and another one which set the state_class incorrectly (known as a mark brain ache bug!).

If you update to latest release, this should be in kWh and be able to be used in the energy functions.

Will close this as already fixed but feel free to reopen if you think not or raise any other issues you find.  Thanks Mark
