### ISSUE TITLE
Heating actuators, shutters, and dimmable light

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#215]
I had asked several weeks ago to be able to implement the Heating actuators systems in the Wiser integration.
Today they are recognized and associated in a room, but I would like to go further with the acquisition of power and cumulative power, as well as the state of the relay ...
The same thing for shutters and light dimmers ...
Mark has done a lot of work, is it possible to continue? 
Of course I am ready to help you by carrying out tests.

**Comment by msp1974** [comment]
We can do more on this yes.  However, i would like to wait until we have done the 3.0.19 release as i have added a function to capture json output from the hub more easily which will make this much easier than your wireshark logs.

I'll message you when this is available and instructions on how to do.

**Comment by LGO44** [comment]
OK thank you
I can share a translation in french
[fr.zip](https://github.com/asantaga/wiserHomeAssistantPlatform/files/7850180/fr.zip)

**Comment by LGO44** [comment]
Hi Mark,
This is no really an issue , but I want to share and to get your feedback

I’m trying to manage this kind of devices.
I start from the 3.0.19 version of the integration and of course the WiserHeatAPIv2
I've an issue, I ask myself if the cause should not be in the WiserHeatAPIv2 because I use the light_id that seems to be not provided by the API.
What do you think about that
Thanks


[Wiser.zip](https://github.com/asantaga/wiserHomeAssistantPlatform/files/7935115/Wiser.zip)
[Description WiserHeat_json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/7935119/Description.WiserHeat_json.txt)
[Donnees WiserHeat.xlsx](https://github.com/asantaga/wiserHomeAssistantPlatform/files/7935122/Donnees.WiserHeat.xlsx)
[My modifications.docx](https://github.com/asantaga/wiserHomeAssistantPlatform/files/7935130/My.modifications.docx)

**Comment by msp1974** [comment]
Ok, having looked at this, its a good start but there are a number of issues. I'll start with your main question and the try and give you some pointers.The wiserHeatAPIv2 does provide the light_id property but you are using the device id property, which is perfectly fine and the way you have enumerated the lights and got the device in the WiserLight class is fine.  However, this is not the issue you have or the error you are getting.Your issue is that your lights.py does not follow what is needed to do a light integration.My best advice would be to not copy the file like you have but look at other integrations that have a light entity.  Each of the HA entity types have quite different requirements for properties and classes and looking at other ones will help you greatly understand what you need to do better.  If you look at the HA supported devices page and select lights, you will see lots of integrations that use this entity.   If you then look at there code in the HA core github repo (under homeassistant/components directory) you can see their light.py files and learn from them.Other point to note is that the wiserHeatAPIv2 does not yet support controlling these lights as i do not know what the control commands are.  However, if you start with your light integration being able to display your light status, get that working, and then we can add the capability to control it with both changes to the api and then to the integration.I would also study the api to see what properties it exposes and therefore link how to use those in the integration to get brightness level etc.Hope that helps.  Reach out again with your subsequent work if you need more help.MarkSent from my Galaxy
-------- Original message --------From: LGO44 ***@***.***> Date: 25/01/2022  16:04  (GMT+00:00) To: asantaga/wiserHomeAssistantPlatform ***@***.***> Cc: Mark Parker ***@***.***>, Comment ***@***.***> Subject: Re: [asantaga/wiserHomeAssistantPlatform] Heating actuators, shutters, and dimmable light (Issue #215) 

Hi Mark,

This is no really an issue , but I want to share and to get your feedback

I’m trying to manage this kind of devices.

I start from the 3.0.19 version of the integration and of course the WiserHeatAPIv2

I've an issue, I ask myself if the cause should not be in the WiserHeatAPIv2 because I use the light_id that seems to be not provided by the API.

What do you think about that

Thanks

Wiser.zip

Description WiserHeat_json.txt

Donnees WiserHeat.xlsx

My modifications.docx

**Comment by msp1974** [comment]
I would also add that using Wireshark is a very hard way to see the json from the hub.  You are far better using Postman or in the wiserHeatAPIv2 there is now a command line option to download the json output and save to file.  This is much easier to read as it is just the json output without any of the wireshark gumf.

Command line for wiser api to output is (you will need to run it in your HA terminal session or download a copy into some other python environment:
```
wiser output [hub ip] [secret key] domain
```

It will save the output json file into a file for you.

**Comment by LGO44** [comment]
Thank you very much Mark for all your help and advices.
I want to participate to the life of your very good integration

**Comment by msp1974** [comment]
I have made a stab at a light.py file for you to give you a bit of a start.  So far, I think it will display your lights and allow you to see if it is on/off and the brightness level.  As said before, you can't currently control them as the api does not support.  I will need you to be able to capture the commands that do this so we can add to the api and then allow HA to control them.  You will see in the code, I have commented out the api function calls for now but this is what will go there when we have them.

I have tested it briefly with our wiser hub emulator and seems to work ok but may have some bugs in it that you will need to work through.

```
"""Support for Wiser lights via Wiser Hub"""
import logging

from homeassistant.components.light import (
    ATTR_BRIGHTNESS,
    SUPPORT_BRIGHTNESS,
    LightEntity,
)
from homeassistant.helpers.dispatcher import async_dispatcher_connect


from .const import DATA, DOMAIN, MANUFACTURER
from .helpers import get_device_name, get_identifier, get_room_name, get_unique_id

MAX_BRIGHTNESS = 100
_LOGGER = logging.getLogger(__name__)

async def async_setup_entry(hass, config_entry, async_add_entities):
    """Add the Wiser System Switch entities."""
    data = hass.data[DOMAIN][config_entry.entry_id][DATA]  # Get Handler

    wiser_lights = []
    if data.wiserhub.devices.lights:
        _LOGGER.debug("Setting up light entities")
        for light in data.wiserhub.devices.lights.all:
            if light.is_dimmable:
                wiser_lights = [
                WiserDimmerLight(data, light.id) 
                ]
        async_add_entities(wiser_lights, True)


class WiserLight(LightEntity):
    def __init__(self, data, light_id):
        """Initialize the sensor."""
        self._data = data
        self._light_id = light_id
        self._light = self._data.wiserhub.devices.lights.get_by_id(light_id)
        self._name = self._light.name
        _LOGGER.info(f"{self._data.wiserhub.system.name} {self._name} init")

    async def async_force_update(self):
        await self._data.async_update(no_throttle=True)

    async def async_update(self):
        """Async Update to HA."""
        _LOGGER.debug(f"Wiser {self.name} Light Update requested")
        self._light = self._data.wiserhub.devices.lights.get_by_id(self._light_id)

    @property
    def is_on(self):
        """Return the boolean response if the node is on."""
        return self._light.is_on

    @property
    def name(self):
        """Return the name of the Device."""
        return f"{get_device_name(self._data, self._light.id)} {self._name}"

    @property
    def icon(self):
        """Return icon."""
        if self._light.mode == "Auto":
            return "mdi:lightbulb-auto" if self.is_on else "mdi:lightbulb-auto-outline"
        else:
            return "mdi:lightbulb" if self.is_on else "mdi:lightbulb-outline"

    @property
    def unique_id(self):
        return get_unique_id(self._data, "device", "light", self.name)

    @property
    def should_poll(self):
        """Return the polling state."""
        return False

    @property
    def device_info(self):
        """Return device specific attributes."""
        return {
                "name": get_device_name(self._data, self._light.id),
                "identifiers": {(DOMAIN, get_identifier(self._data, self._light.id))},
                "manufacturer": MANUFACTURER,
                "model": "NHPDimmer",   #This needs api update
                "sw_version": "020519ff",   #This needs api update
                "via_device": (DOMAIN, self._data.wiserhub.system.name),
            }

    async def async_added_to_hass(self):
        """Subscribe for update from the hub."""

        async def async_update_state():
            """Update light state."""
            await self.async_update_ha_state(True)

        self.async_on_remove(
            async_dispatcher_connect(
                self.hass, f"{self._data.wiserhub.system.name}-HubUpdateMessage", async_update_state
            )
        )


class WiserDimmerLight(WiserLight):
    """A Class for an Wiser light entity."""
    def __init__(self, data, light_id):
        """Initialize the sensor."""
        super().__init__(data, light_id)

    @property
    def supported_features(self):
        """Flag supported features."""
        return SUPPORT_BRIGHTNESS

    @property
    def brightness(self):
        """Return the brightness of this light between 0..255."""
        return self._light.current_percentage

    async def async_turn_on(self, **kwargs):
        """Turn light on."""
        if ATTR_BRIGHTNESS in kwargs:
            brightness = int(kwargs[ATTR_BRIGHTNESS])
        else:
            brightness = self.brightness
        if brightness is not None:
            # Below functions need adding to api first
            """
            await self.hass.async_add_executor_job(
                setattr, self._light, "brightness", brightness
            )
            """
            pass
        else:
            """
            await self.hass.async_add_executor_job(
                self._light.turn_on
            )
            """
            pass
        await self.async_force_update()
        return True

    async def async_turn_off(self, **kwargs):
        """Turn light off."""
        # Below function needs adding to api first
        """
        await self.hass.async_add_executor_job(
            self._light.turn_off
        )
        """
        await self.async_force_update()
        return True

    @property
    def extra_state_attributes(self):
        """Return the device state attributes for the attribute card."""
        attrs = {}
        # Add any attrs here
        return attrs
```

**Comment by LGO44** [comment]
Thanks a lot Mark, 
Your proposal is OK , I’ll test it next days 
and give you my feedbacks

**Comment by LGO44** [comment]
Hello Mark,

I've made some tests with your integration, here re my results
[Tests light.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/7979757/Tests.light.pdf)

**Comment by msp1974** [comment]
Not very clear on what your test results are saying.  I have created a branch called light_dev.  Are you able to submit a PR with changes that are needed?

Also, are you able to provide what the commands are for contolling the lights sent by the app?

**Comment by LGO44** [comment]
Sorry for not being clear.
I used your light.py and I test it.
 
I've made some modifications underlined in yellow in my doc, the variable "BRIGHTNESS" move from 0 to 255 , it's "BRIGHT_PCT" (Brightnees percentage" that is used in the light card.

I've gone on on my first idea , to derivate the light.py from your climate.py for several reasons:

-  it's possible to adjust the brightness as the light is on
- it's possible to use a schedule ( like smart plug and climate...)

From my point of view, the wiserHeatAPIv2 should get all the data provided by the hub, even if your integration doesn't use them.

I'll put my work in the branch light_dev this afternoon

**Comment by LGO44** [comment]
here is a zip file of my wiser folder with the light.py , cover.py ... files
Those two file are built derivate from climate.py 

With the shutters (cover file) I've a problem only the last shutter is  created, I think that it's the same for the light ( but I have only one).

Next week I won't be as available as I want 
[wiser.zip](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8006596/wiser.zip)

**Comment by LGO44** [comment]
here is the last zip file of my wiser folder with the light.py , cover.py ... files based on the 3.0.20 version
Those two file are built derivate from climate.py

With the shutters (cover file) I've a problem only the last shutter is created, I think that it's the same for the light ( but I have only one).

[wiser.zip](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8010028/wiser.zip)
.

**Comment by msp1974** [comment]
OK.  I need to look through this properly but the issue of only having one shutter/light is that you need to append to the array - you are just setting it and therefore overwriting it apart from the last one.  I may have had this error in what I sent you - sorry!

```
wiser_lights = []
    if data.wiserhub.devices.lights:
        _LOGGER.debug("Setting up light entities")
        for light in data.wiserhub.devices.lights.all :
            if light.is_dimmable:
***HERE***      wiser_lights.append = [
                WiserLight(data, light.id ) 
                ]
        async_add_entities(wiser_lights, True)
```

**Comment by msp1974** [comment]
Also,  lets leave this issue open as we work through it.  Will reopen.

**Comment by LGO44** [comment]
Thanks Mark,
i tried your code for light and cover:
    __wiser_lights = []
    if data.wiserhub.devices.lights:
        _LOGGER.debug("Setting up light entities")
        for light in data.wiserhub.devices.lights.all :
            if light.is_dimmable:
                wiser_lights.append = [
                WiserLight(data, light.id ) 
                ]
        async_add_entities(wiser_lights, True)__
       

__
results:
![image](https://user-images.githubusercontent.com/95585425/152684848-7d3b72a0-f6b5-4409-a4dd-75a0a9824e2c.png)

**Comment by msp1974** [comment]
Its because you define _wiser_lights but append to wiser_lights.  You need to make these the same name.Sent from my Galaxy

**Comment by LGO44** [comment]
Ok now

 for light in data.wiserhub.devices.lights.all :
            if light.is_dimmable:
                wiser_lights.append (
                WiserLight(data, light.id ) 
               )
        async_add_entities(wiser_lights, True)

**Comment by LGO44** [comment]
I can monitor now my lights and shutters but I cannot command them.

To complete the ligth I propose you to add these attributes in the light.py into the wiserHeatAPIv2:
    """ Added by LGO44  """  
    @property
    def schedule_id(self):
        """Get the schedule id of the light"""
        return self._device_type_data.get("ScheduleId", 0)
    
    @property
    def manual_level(self):
        """Get the manual level of WiserLight"""
        return self._device_type_data.get("ManualLevel", 0)
        
    @property
    def output_range_minimum(self):
        """Get the minimum range for the level of WiserLight"""
        return self._device_type_data.get("OutputRange", {'Minimum': 0}).get("Minimum")
        
    @property
    def output_range_maximum(self):
        """Get the maximum range for the level WiserLight"""
        return self._device_type_data.get("OutputRange", {'Maximum': 0}).get("Maximum")
        
    @property
    def target_state(self) -> str:
        """Get the light target state On Off"""
        return self._device_type_data.get("TargetState", 0)
        
    @property
    def target_percentage(self) -> int:
        """Get the light target percentage"""
        return self._device_type_data.get("TargetPercentage", 0)
        
    @property
    def scheduled_percentage(self) -> int:
        """Get the light scheduled percentage"""
        return self._device_type_data.get("ScheduledPercentage", 0)
        
    @property
    def override_level(self) -> int:
        """Get the light override level"""
        return self._device_type_data.get("OverrideLevel", 0)




To complete the shutter I propose you to add these attributes in the shutter.py into the wiserHeatAPIv2:
    
""" Added by LGO44  """  
    
    @property
    def schedule_id(self):
        """Get the schedule id of the light"""
        return self._device_type_data.get("ScheduleId", 0)
    
    @property
    def target_lift(self) -> int:
        """Get the light target lift"""
        return self._device_type_data.get("TargetLift", 0)

To command the device the turn_on and turn_off  functions have to be implemented in the API.

For the lights I think that we have to modify the current_level to increase or decrease the brightness , and modyfy the current_state On or Off to switch On or switch off the light.

For the shutters I think that we can modify the position and we have also  a switch to open  another to shut and a third command to stop.

**Comment by LGO44** [comment]
My previous comments are obsolete, the job had been already done.
I'm sorry but I think that I don't use the last version of the API.

How can't I update the API? how can I know what version do I use?

- I have just clone the last repo, It had create a wiserHeatAPIv2 folder in the config folder.

![image](https://user-images.githubusercontent.com/95585425/153609340-a2529528-4cb8-416c-b1cf-bc384c746fe6.png)

When I try to run the _wiser output [hubIP] [secret] domain_ it failed because the command is not known

![image](https://user-images.githubusercontent.com/95585425/153610018-55d0a0f3-2a22-45ac-b754-88cd4e03a729.png)

When I try to tests the API I got the results below:
![image](https://user-images.githubusercontent.com/95585425/153611370-2bf2744c-eec3-4522-b8a3-70f289d47316.png)

Thanks in advance for your help

**Comment by msp1974** [comment]
OK.  Quite a few things here but I'll try and answer them all.

Firstly, I think you need to create a development environment for doing this as otherwise you could trash you live HA environment by needing to update to untested API or integration code.

You also need to understand how to use Github - it will make your life much easier.  This way, you will be able to fork the api and integration repos, clone these to your development setup, play/code etc, push the updates back to your repo and submit PRs to get changes into the main release.

In order to use the latest version (or a dev version) of the api, fork it to your repo and then clone from your repo to whatever development environment you are using.  You then need to install it into the python environment you are developing with.  If you google how to install a python package from a cloned repo you will find loads of helpful walk throughs.

You are getting an error trying to run the wiser command line because the api is not installed in the python environment you are trying to run it in.

You are getting an error trying to run the tests because you have not quoted the IP address of your host ie HOST="10.0.0.18"
However, this will also error (once you fix the above) because it will not be able to find the wiserHeatAPIv2 as it is not installed.

As a help for you, I have released v3.0.21 tonight which will install the latest api with the changes in into your HA python environment.  It also now has a service to output your hub json to 3 files in a wiser_data directory in your HA config directory (your wireshark outputs are really hard to use) - this should make understanding all the property values much easier.

As a final point, in order to understand the required commands to be able to add control of your lights/shutters etc, you will need to install HTTPCanary onto an Android device with the wiser app.  It seems it is not available on the Play Store at the moment but there are other places you can download it from.  I use this to capture http requests to the hub from the wiser app to decifer the commands.  Unfortunately, as I don't have and can't get these devices, I cannot do this for you.

Sorry this is long, but I think if you spend some time setting up a proper development environment and learn to use github etc, the next steps of the process to get all this working will be much simpler.

Mark

**Comment by LGO44** [comment]
Thanks a lot Mark
I've used the **Drayton Wiser Integration for Home Assistant: output_hub_json**. I'll give you the data; very easy to do it should be nice to have the same warning than for the  Remove Orphaned Devices

![image](https://user-images.githubusercontent.com/95585425/154368982-f2e20d53-3336-4588-93d9-2f7939308f63.png)

 instead of

![image](https://user-images.githubusercontent.com/95585425/154369207-cfa306bf-dafc-47bb-8437-143a68bd7e38.png)

It should be like we say in France "The cherry on the cake"


I'm creating a Github repository to share all my job with you. You will find in the wiser_data, and a file with the commands got by HTTPCanary.

All this will be available tomorrow.

Christian

**Comment by msp1974** [comment]
> 

Great - that will make it much easier to progress on this.  On the images above, I think you might need to do a browser refresh as it should look like this.

![image](https://user-images.githubusercontent.com/11211952/154524334-bd941df4-c8d6-40c0-8c27-47fcbddbdc84.png)

or in yaml edit mode
![image](https://user-images.githubusercontent.com/11211952/154524425-dd7f3e4f-9f21-489d-ab88-bb52a4720959.png)

**Comment by LGO44** [comment]
I have created a repository on Github
here is the link
LGO44/wiserLightsShutters
Thanks again
Christian

**Comment by msp1974** [comment]
OK, having the data in json format and getting the commands from the app with HTTPCanary is much easier to work with.  I have updated the wiserHeatAPIv2 api to now have commands to turn on/off and adjust the brightness level (current_level) for lights.

Also added open, close, stop and current_lift methods/properties to control shutters.

You will need to clone from the wiserHeatAPIv2 repo - https://github.com/msp1974/wiserheatapiv2 to get the latest v0.0.21.  You can google how to install this once cloned into your dev env.

**Comment by msp1974** [comment]
@LGO44 can we keep all updates relating to this on this issue so we can keep track.

Have been working more on the API this morning and updated the github repo.  As such you will need to do a git pull to get the latest version into your clone and then re-install.  I would advise using:
```
pip install -e .
```
from your clone directory in the python environment you are running your dev in (dont forget the . at then end!)

In terms of your github repo, I was really expecting you to fork the asantaga/wiserHomeAssistantPlatform and then checkout the lights_dev branch so that we can work on that together.  Me provide some updates, you push PRs with your updates etc.

You will see that I have done some work on the lights.py and covers.py for you in that branch, which I think you could then test with the latest api pull and it should all work (he says! ;-)).  For now, I have commented out some of the schedule functionality so that we can tackle that once we have the basics working.

**Comment by msp1974** [comment]
Just to add.  Below link is how I have my dev environment setup and it is pretty easy to use and work with as we are doing on this.

https://developers.home-assistant.io/docs/development_environment#setup-local-repository

**Comment by LGO44** [comment]
@msp1974
Hello Mark
A clarification on my work environment:
 I work on a linux virtual machine, Virtual Box, with Home Assistant installed from the Linux site - Home Assistant (home-assistant.io) [https://www.home-assistant.io/installation/linux]. I started with a 6.6 version that I keep up to date.
So I work in this environment. This is a test platform, I have another Home Assistant that runs on a Raspberry Pi 4.

I installed a development environment, as you suggested to me on Saturday see the attached file.
![image](https://user-images.githubusercontent.com/95585425/154866464-d1dae415-af2b-4041-88d3-9f898e215824.png)


I continued my tests and I still get errors. See logs.

2022-02-20 22:15:26 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140161718362608] '_WiserLight' object has no attribute 'turn_off'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 513, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/wiser/light.py", line 372, in async_turn_off
    self._light.turn_off
AttributeError: '_WiserLight' object has no attribute 'turn_off'

I think the problem is that I installed the new version of wiserHeatPIv2 correctly in the dev environment that I have created while I am using a Linux virtual machine in VBOX.

[Install wiserHeatAPIv2  and HA dev environment.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8105026/Install.wiserHeatAPIv2.and.HA.dev.environment.pdf)

Thanks

**Comment by msp1974** [comment]
Sorry - posted on wrong issue

@LGO44 - your dev environment is not the right way to run a dev environment for HA. This is actually a way to run a deployed version, it is running HA in a docker container, not on the base OS and the terminal session you are running in not actually in the HA python environment, therefore, whilst what you are doing is correct to install wiserHeatAPIv2, you are not actually installing it into the python environment that HA is using.

My recommendation would be to build a linux environment in vbox (I run under and Ubuntu environment with a GUI), and then follow the instructions on the link I gave you about setting up a dev environment (looks like you were trying to do this within the Hass OS environment - which is very wrong).

Once you have a base Ubuntu install, then follow the instructions on this link. You should not have any HA environment before you follow these instructions.

https://developers.home-assistant.io/docs/development_environment/#setup-local-repository

**Comment by msp1974** [comment]
Just to help you along with this.

Build a vbox of Ubuntu - use Ubuntu Desktop 20.04 download.
Once installed and all updates run
Ensure you have python3.9 installed - lots of instructions on web to do this if not already installed.  You can check by running - 
```
python3 --version
```

**Installing HA**
I create a folder in my home drive called development to put all my cloned repos relating to this and develop against these files.
From within your development folder, setup HA as per these instructions
https://developers.home-assistant.io/docs/development_environment/#setup-local-repository
Run it, log in via browser and create your user id etc.
Essential that you know this is all working before progressing.
Do not add anything else to your HA environment at this point.

**Installing wiser**
Clone your wiser integration repo - 
```
git clone https://github.com/LGO44/wiserLightsShutters.git
```
Go to home/[your user]/development/core and create a custom_components folder if it doesn't already exist.
In that custom components folder, create a symbolic link to the wiser directory - this will allow you to update the files in the development/wiserLightsShutters folder and HA will use them after a restart. - 
```
ln -s /home/[userid]/development/wiserLightsShutters wiser
```

Restart HA and ensure that the wiser integration is working (ie it discovers your hub in the integrations page).
If there is an issue, you will see it in the terminal window where you are starting HA as all log info is written to the screen.
At this point setup your wiser hub with your secret key.

**Using the latest unreleased version of wiserHeatAPIv2**
Again in your development directory (not in core of wiserLightsShutters folders)
Clone the wiserHeatAPIv2 repo into this development directory - git clone https://github.com/msp1974/wiserHeatAPIv2.git
Go to your HA python environment and install the package
```
cd ~/development/core
source venv/bin/activate
cd ~/development/wiserHeatAPIv2
pip install -e .
```

You will also need to amend the manifest file of the wiser integration to allow a higher version of the api
```
cd ~/development/wiserLightsShutters
nano manifest.json
```

change the line
```
"requirements": ["wiserHeatAPIv2==0.0.20"]
```
to
```
"requirements": ["wiserHeatAPIv2>=0.0.20"]
```

Now start your HA environment and you should be running your integration code with the 0.0.21 version of the api.

Few other notes to help you

1) I use VSCode to develop in this environment.  Very easy to use and a great IDE.  You can also config it to do all your git commits etc
2) Only amend the files in your development folder.  They will all apply in HA when you restart it
3) To validate the version of the API you are using, look at the screen output when you are running HA, scroll up and you will see something like this
```
2022-02-19 14:00:00 INFO (SyncWorker_3) [wiserHeatAPIv2] WiserHub API v0.0.21 Initialised - Host xxx.xxx.xxx.xxx, Units: Metric
```

Hope this is clear and helps you get an environment setup.  Once you have the hang of it, it is not too complicated and certainly will make developing this much easier for you.

**Comment by LGO44** [comment]
@msp1974 
With your informations I regain my confidence. THANK YOU.
I followed your recommendations and it actually seems more efficient to me.
I have created a virtual machine  Ubuntu in Virtual Box , I have also updated It, install python 3.9 ....
However, after installing the HA development environment, having created a Python 3.9 virtual environment, I cannot launch HA using the command **hass -m config** .

![image](https://user-images.githubusercontent.com/95585425/155116959-b871001b-2e3a-458f-a0b0-59988a68835f.png)

What do I do wrong? Do you have any idea?

**Comment by msp1974** [comment]
It's hass -c configGlad that is better for you.Sent from my Galaxy

**Comment by msp1974** [comment]
You also need to be in the core directory not my_envSent from my Galaxy

**Comment by msp1974** [comment]
Can you post a screenshot of this files in this directory.  Have you followed all the steps exactly from the HA instructions?
https://developers.home-assistant.io/docs/development_environment/#setup-local-repository

NOTE:  apologies for previous post from my phone.  The command is
```
hass -c config
```
Not configGlad as it says due to poor typing!

**Comment by LGO44** [comment]
I have followed exactly the indications of the site
https://developers.home-assistant.io/docs/development_environment/#setup-local-repository

I have also install Python3.9 following the site:
https://askubuntu.com/questions/1347748/how-to-install-latest-version-of-python-3-9-5-on-ubuntu-20-04 

You will find by the screenshot yhe content of the folder development, core and homeassistant 
![image](https://user-images.githubusercontent.com/95585425/155213520-ae412d2b-bfae-45aa-a283-b84abc3e461b.png)

I've follow your last indications:

-  deleting core folder
-  reinstall home assistant core
-  try to launch HA    ==>no improvement
-  reinstall Python3.9
- Try again to run HA 

Always the same result 
I have made an HTML file of all the commands


[Last operations.zip](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8119984/Last.operations.zip)

**Comment by msp1974** [comment]
I think there are a few issues here.

1) You are getting confused re setting up a venv environment on pyrhon3.9
2) It looks like the script/setup is failing which is why hass command does not work.

I will run up a new ubuntu environment tomorrow and get this setup so i can send you detailed instructions as not quite sure why script/setup is not working.

**Comment by msp1974** [comment]
Christian,

I have run through a setup from scratch (its been a while since I have done this) and laid out below all the steps.  I have done it as if it were a brand new Ubuntu install but there is no harm in running all these steps as they are written in your existing one.  I would delete the ~/development/core folder before you start.

```
sudo rm -R ~/development/core
```

1) Ensure you Ubuntu is fully up to date
```
sudo apt update
sudo apt upgrade
sudo reboot
```

2) Install Vbox guest additions - this has drivers etc for screen sizing and allows you to copy and paste these commands into a terminal window.
```
sudo apt install gcc make perl git
```
In vbox ubuntu window go to Devices->Insert Guest Additions CD image
You should be prompted to install vbox guest additions – Run
Make sure there is no error installing in the output on screen and close window as prompted.
```
sudo reboot
```

3) Install python3.9 and all other dependencies for Home Assistant
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.9
sudo apt-get install python3-pip python3.9-dev python3.9-venv autoconf libssl-dev libxml2-dev libxslt1-dev libjpeg-dev libffi-dev libudev-dev zlib1g-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev ffmpeg
```

4) Setup your Home Assistant environment
```
cd ~/development
git clone https://github.com/LGO44/core.git
cd ~/development/core
python3.9 -m venv venv
script/setup
source venv/bin/activate
```

5) Run Home Assistant Server
```
hass -c config
```

Depending on your machine speed, it will take a minute or 2 to first run but you should then be able to connect to it via a browser.
Ctrl-C to terminate server from terminal window

To run server again after stopping
```
cd ~/development/core
source venv/bin/activate
hass -c config
```

If you change any of the integration code, you will always need to restart the server to pick up new code.

**Comment by LGO44** [comment]
@msp1974 THANK YOU VERY VERY MUCH for all your help and availabilty.
I scrupulously followed your recommendations and as usual I obtained the expected result.
I think the key to the problem came from the non-installation of the Virtual Box tools which prevented the proper execution of the script/setup.
I apologize for coming back to you so late but I'm continuing my tests... and time flies

Following your advice I installed VS Code and I am very satisfied.

Retired for a few months, (a career in the world of industrial automation), thanks to you I am learning new things (Python, Github, Vscode, Linux...) and to share with a team ( I hope I can bring my stone to the construction of your Wiser integration and provide some return on investment
Truly THANK YOU for everything
Christian

**Comment by msp1974** [comment]
@LGO44 - you have been very quiet lately.  Are you making progress?  Do you need any more help?

**Comment by LGO44** [comment]
@msp1974
I 'm making progress , sorry I could surely be more efficient but I'm only a beginner.
   I have made some modifications in the API to get more properties...
  Now the lights as the shutter can be simply managed by HA, I have a problem with the light card that seems to not write brightness 
  I've created LTS sensors fore power and energy provide by the heating actuator...
 I will try to update the GitHub tomorrow on on friday so you could have a look on my job 
your remarks will be welcome of course.
than

**Comment by LGO44** [comment]
@msp1974 
on my github repositories I share my last version of 

- wiserHeatAPIv2 build your version v0.0.21
       https://github.com/LGO44/wiserHeatAPIv2/tree/LightsShutters_Dev-

- wiserLightsSutters build on the version v3.21 and reported in the version 3.24
      https://github.com/LGO44/wiserLightsShutters/tree/Dev-tests
My development environment is based on these 2 initial versions.

Questions: 
 I have 5 wiser shutters at home , they appear in a collection of cover not as 5 devices, is it possible to get them as  devices? 
It should be the same for lights, but now I have only one.

Knowned issues:
1.   the service get schedule for lights and shutters give allways a file with only null in the first line
2. I cannot turn_on the light when I modify the brightness in the light-card
3. I cannot turn_on the shutter when I modify the position


I have tested wiserlightsShutters_dev in a V0.0.24 wiser integration in my docker (alpine) machin but it doesn't run perfectly (the installation of my wiserheatAPIV2 V0.0.24.1 is not correct I think) .

I will upgrade my development environment to the version V0.0.24 of wiserHeatAPIv2 and report my improvment , 
Have you update the dev lights in version 3.0.24?

feel free for any remarks and questions
Thanks 
LGO44

**Comment by LGO44** [comment]
Last informations:
I have installed the wiserHeatAOIv2 v0.0.24 in my development environment , then carried over my changes made in the v0.0.21 version.
The branch LightsShutters_dev- of rhe wiserHeatAPI available in my Github repository is up to date
    https://github.com/LGO44/wiserHeatAPIv2/tree/LightsShutters_Dev-

It works fine with this version .
