### ISSUE TITLE
Heating toggle

### ISSUE THREAD

**Issue by willhaggan** [asantaga/wiserHomeAssistantPlatform#222]
Hi is it possible to control just the heating channel on the 2 channel wiser heating hub. The hot water toggle works perfectly

**Comment by msp1974** [comment]
Sorry, not sure i understand.  Can you elaborate.

**Comment by asantaga** [comment]
if you want to control the heating channel then the right way is to prod the trvs, ie boost which ever one you want.. 

Wiser is a zoned system not heating on/off .. hotwater is different

**Comment by willhaggan** [comment]
Hi you cannot directly control the heating relay on the heat hub only the hot water relay 
I understand it should be used with wiser trvs, but in my case I am using the heat hub only with different brand trvs and temperature sensors.

**Comment by asantaga** [comment]
ah i get it, right wiser doesnt allow this but a cheap and easy workaround is to buy a single TRV then you can set the temp to 10C for off and 30C for on :-)

**Comment by msp1974** [comment]
There is a button on the hub to turn the heating on.  I'll have a play with my test hub (as it has no trvs etc) to see if there is a command that turns this on (ala the HW command is equivalent to pressing the HW button).  Wiser app doesn't do this so maybe not.Otherwise, yes concur with Angelo it is designed to have either Roomstats or TRVs and is sold with them.  Maybe a roomstat would be best option for you and theb as Angelo says, you can boost for x time or turn on/off by setting temps to 5C/30C.Sent from my Galaxy

**Comment by willhaggan** [comment]
Hi there, thanks for the update.
You can get the heating on by holding it for 5 seconds but this is just an override as you probably know.

I can just wire the heating signal into the HW relay no issue but would have preferred to have both.

I currently have a similar setup but with salus it600 boiler controller and one of their stats which I just set to heat from HA when my other trvs need heat which in turn sets the boiler on. It works fine but would rather have direct control 

The salus integration does not give you direct access to the controller switch like the wiser integration.

**Comment by willhaggan** [comment]
> ah i get it, right wiser doesnt allow this but a cheap and easy workaround is to buy a single TRV then you can set the temp to 10C for off and 30C for on :-)

Yea good idea similar to what iam doing with my salus setup.

**Comment by asantaga** [comment]
Closing for now, let us know how well this works, might be interesting for others
