### ISSUE TITLE
Pairing to drayton servers recommended/required

### ISSUE THREAD

**Issue by james-cook** [asantaga/wiserHomeAssistantPlatform#239]
I have finally installed wiser!

I set it up directly via the hub without registering for remote access (well in my case the step didn't work). I can access the schedule in the app via the hub's own "access point".
This leads me to wonder, is the pairing step for remote access with Drayton absolutely necessary or recommended?

The answer may be obvious, but does this software interface directly with the hub or via Drayton's servers?

If it is directly, do I lose much by not registering with Drayton's servers. I suppose I miss out on hub updates etc.

My goal is to access the home automation on a raspberry pi via port forwarding.
Registering with Drayton would give me a fail safe if the raspberry went down.

Thanks for your thoughts/guidance

**Comment by msp1974** [comment]
James - welcome to the Drayton user community!

This software interfaces directly with the hub. The hub is pretty self contained meaning if you RPI goes down, it will continue to function with all prior settings and you can adjust settings with the app so long as you are on the same lan.

You do need to register and connect your hub to the cloud to get software updates - which are sporadic but do add new functionality that the integration may rely on in the future.  We have only had 1 prior issue due to hub software version but we have no idea how many do not connect hub to Wiser cloud.

Unless you have a strong aversion to it, I would recommend connecting to cloud even though integration does not need it just to keep all your devices (hub, TRVs, Roomstats etc all have firmware) updated.

**Comment by asantaga** [comment]
ditto! ( iwas just writing the same!)

**Comment by james-cook** [comment]
Wow!

Thanks for these very quick(!) replies.
It is very good to know that the hub is interfaced directly. 

One main reason I went for wiser was exactly the fact that the schedule is on the hub itself and will continue to run :) Internet and even electricity can be flaky here!

Yes, I was wondering if updates would break HA. It seems the benefits of updates outweigh those risks.

My other thought would be privacy. Drayton having EVERYDAY insight into my home/schedule/devices etc. For these concerns I was thinking (at some point) of allowing access to Drayton only periodically. This may have been discussed elsewhere already?
