### ISSUE TITLE
feature request: SmartPlug reset energy button

### ISSUE THREAD

**Issue by nottledim** [asantaga/wiserHomeAssistantPlatform#257]
I mentioned this in passing in #233.

It would be useful to have a button or service to reset the total power (aka energy) reading on the SmartPlug,  assuming that it's possible.

**Comment by msp1974** [comment]
I dont know if this is possible or not.  I do not know a command to do this and cannot see anywhere in the app this can be done.  Does it keep the total if you repower it?

**Comment by asantaga** [comment]
From memory the smart plug looses all its "power" values when its turned off at the main plug.
As mark says the UI doesnt have the power values ..

I dont use it as a smart plug though, simply as a wiser zigbee repeater :-(

closing this as I dont think we can do anything here.

**Comment by nottledim** [comment]
"looses all its "power" values when its turned off at the main plug" I'll stack one underneath so I can turn it off remotely :-)  It doesn't surprise me it can't be done.  It's interesting that the Wiser app doesn't even display the power readings; implies it's not a supported feature anyway.

Thanks for thinking about it.

**Comment by asantaga** [comment]
hey no worries, I was going to suggest you could stack a smartplug under a wiser smartplug 

However I have concerns about doing this, not because of power but the wiser plugs also act as a trv repeater (zigbee). If you turn the whole plug off then you'll loose your repeater functionality, some itrvs might not like it
