### ISSUE TITLE
wiser.climate platform error on Hassio 0.96.2

### ISSUE THREAD

**Issue by naylogj** [asantaga/wiserHomeAssistantPlatform#27]
The climate platform has been re-architected in V 0.96 of Home Assistant.  Please see this link: https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html 

Unfortunately, this means that the climate platform no longer loads.  This is the error in the log file:

2019-07-21 11:59:38 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform wiser.climate: Platform not found (cannot import name 'STATE_AUTO' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)).

I am running V 0.96.2 of HA and the lastest release of the wiser custom component.

Keep up the good work.  Thanks.

**Comment by asantaga** [comment]
Ah,.. Yes..  Thanks for the notice and I'll look at this asap....

**Comment by asantaga** [comment]
fixed in commit https://github.com/asantaga/wiserHomeAssistantPlatform/commit/467a5e1a9455f8d0a2c116b0ad4bb4368db5d5db 

Ive also now rev'd everything to v1.4. This includes a bunch of fixes/features I was working on in a seperate branch. Namely 
- Now uses pypi package Ive written
- Prepped code for inclusion into HA native
- Fixed a refresh bug
- and of course now compatible with 0.96.x of HA.

thanks!
