### ISSUE TITLE
Async error: AttributeError: 'WiserAwayModeTempNumber' object has no attribute '_attr_value'  

### ISSUE THREAD

**Issue by GSzabados** [asantaga/wiserHomeAssistantPlatform#271]
Running HA 2022.6.7 and the latest and greatest version of this integration 3.1.

The following error pops up in the logs, Away temperature used to be set to 16 C, now it cannot read it.

```
2022-07-10 12:24:32 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update_state when dispatching 'WiserHeat02B2D4-HubUpdateMessage': ()
Traceback (most recent call last):
  File "/config/custom_components/wiser/number.py", line 96, in async_update_state
    await self.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 170, in state
    return self.value
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 175, in value
    return self._attr_value
AttributeError: 'WiserAwayModeTempNumber' object has no attribute '_attr_value'
```

**Comment by msp1974** [comment]
It seems that changes in the number component in 2022.7 are not backward compatible to 2022.6.x.  if you upgrade to 2022.7 this will work.

**Comment by msp1974** [comment]
Sorry didnt mean to close.  Leave open to remind me to log a core issue

**Comment by GSzabados** [comment]
Thanks Mark! I appreciate that!

I have even updated the value in the Wiser app to 15 C and it is still has the error. Bummer than, I haven't read about that as a breaking change.

**Comment by GSzabados** [comment]
Actually there is a change logged for Number entity:

https://developers.home-assistant.io/blog/2022/06/14/number_entity_refactoring/

**Comment by msp1974** [comment]
Its not that change but one that has not been mentioned in the release notes.  You will see an issue on this repo #268 that is logging a deprecation warning.  This is on the number integration.

We updated the code to stop this but that seems to break the number entity on any version less than 2022.7.  Unfortunately, only realised this after release of 3.1.0 when i updated my prod HA from HACs which was on 2022.6.6.  Updating it to 2022.7.2 fixes.

Did try to work out how to have code compatible with both versions but can't seem to find a solution, which is why need to log core issue.  Will spend some more time trying to work it out.

Hate forcing people to upgrade HA when we do an update to the component but think that maybe the only answer in this case or wait until HA provide a fix in a 2022.7.x version.

Sometimes opensource is not perfect!

**Comment by msp1974** [comment]
Oh sorry, yes it is that change

**Comment by GSzabados** [comment]
> Oh sorry, yes it is that change

It is mentioned at the end of the Blog post. That's where I got the link from.

**Comment by GSzabados** [comment]
> Sometimes opensource is not perfect!

No worries. This is not a big deal. I just rolled back to 3.0.24 for the sake of no errors.

The recent Supervisor update from 2022.05.X to 2022.06.2 was more of a hit, as it failed to start on older versions of Docker which hasn't defined the CGroupVersion. It just ran into an error and didn't start. Fortunately 2022.07.0 solved it, but it gave a lot of grief for many people, as the Supervisor updates automatically.

**Comment by msp1974** [comment]
OK.  Now logged issue on core #74883

**Comment by msp1974** [comment]
I have fixed this issue by reverting the change made in v3.1.0 in v3.1.1 - released.  For now it will just have to show the deprecation warning and a future release will force an upgrade to at least 2022.7
