### ISSUE TITLE
[Feature] Add support into better thermostat

### ISSUE THREAD

**Issue by ryanm101** [asantaga/wiserHomeAssistantPlatform#328]
https://github.com/KartoffelToby/better_thermostat/issues/643

**Comment by asantaga** [comment]
I checked out better_thermostat, and Ive not tried it but I think its already compatible with Wiser through this integration. 
From what I understand/think, if you set all the WIser iTRVs to manual (Heat) mode, then the better_thermostat software can control each trv instead of wiser. 

I dont think there is anything we need to do from this integration

Closing for now, but let me know if Ive misunderstood the requirements
