### ISSUE TITLE
Question/help: How to use the API to view system logs?

### ISSUE THREAD

**Issue by cunningr** [asantaga/wiserHomeAssistantPlatform#338]
I am looking to use the API to explore the DraytonWiser system in order to debug some 'unexpected behaviour'.  I was wondering if you might be able to help me locate the system logs once I get connected to the API?

**Comment by msp1974** [comment]
Not sure about this.  Will look into it as I can see that you can send system logs to Wiser.

**Comment by cunningr** [comment]
Thanks for taking a look.  I am lacking details on how the system actually works to be honest.  I say the "upload logs" in the app and assumed it was pushing them from the hub.

Do you happen to know what the model is for getting data into the Wiser cloud?  I.e Is there a cloud agent polling the hub data over a secure (outbound) tunnel or can we set the Hub up to push data periodically to an API endpoint?

**Comment by msp1974** [comment]
AFAIK the hub does create a connection to the cloud and the cloud agent polls for hub data periodically or when the app uses the cloud connection instead of the local one.  The hub api is a rest api in that it requires a request and cannot be made to push data.

I'll close this issue but please feel free to post in our forum.  If you want to use the api directly and not via HA, the documentation for it is https://github.com/msp1974/wiserHeatAPIv2/blob/master/docs/info.md
