### ISSUE TITLE
Question: how to stop Radiator Thermostats coming on randomly

### ISSUE THREAD

**Issue by DrJohnT** [asantaga/wiserHomeAssistantPlatform#339]
I am having more an more problems with the Wiser Radiator Thermostats that decide to randomly switch on.  In Home Assistant and also in the Wiser App, the Radiator Thermostat will appear off, yet the radiator is clearly on.  No one is in the room, so they have not been tampered with.  At first I thought it was due to batteries, but having replaced the batteries in all Radiator Thermostats, I am still getting the problem.  I also thought it might be because the Radiator Thermostat had come loose.  But now, my wrench will not tighten them up any further.

It today's economic climate, it is even more important not to waste heat on rooms with no one in, so this is real annoyance.

This is not an issue with the Wiser integration, more a problem with the Wiser kit.

I was wondering if recalibrating the Radiator Thermostat might help, but I could not find instructions that worked.

Just wondering if anyone else had this problem and if there is a solution?!?

**Comment by scooper1** [comment]
If batteries below 50%and this happens then problem is normally battery to low to fully close after a valve protection cycle.  Turn off valve protection to lessen the problem

I always find changing batteries after this random heating radiator fixed the problem while caning batteries I always check valve is not stuck or very tight

**Comment by chris-github1975** [comment]
I had a similar issue. I deleted the valve from the wiser app and reinstated it. Effectively the valve was stuck open.


Hope that helps.
Regards
Chris



________________________________
From: Dr John Tunnicliffe ***@***.***>
Sent: Sunday, 8 January 2023, 17:18
To: asantaga/wiserHomeAssistantPlatform ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [asantaga/wiserHomeAssistantPlatform] Question: how to stop Radiator Thermostats coming on randomly (Issue #339)


I am having more an more problems with the Wiser Radiator Thermostats that decide to randomly switch on. In Home Assistant and also in the Wiser App, the Radiator Thermostat will appear off, yet the radiator is clearly on. No one is in the room, so they have not been tampered with. At first I thought it was due to batteries, but having replaced the batteries in all Radiator Thermostats, I am still getting the problem. I also thought it might be because the Radiator Thermostat had come loose. But now, my wrench will not tighten them up any further.

It today's economic climate, it is even more important not to waste heat on rooms with no one in, so this is real annoyance.

This is not an issue with the Wiser integration, more a problem with the Wiser kit.

I was wondering if recalibrating the Radiator Thermostat might help, but I could not find instructions that worked.

Just wondering if anyone else had this problem and if there is a solution?!?

**Comment by msp1974** [comment]
As you say, not an integration issue.  You are much better raising this on the forum page as more people will see and respond.  Closing here.
