### ISSUE TITLE
Provide climate attributes as individual sensors 

### ISSUE THREAD

**Issue by Kallb123** [asantaga/wiserHomeAssistantPlatform#353]
The climate entity has a lot of attributes, many of which would be good to track history. If these attributes were, additionally, provided as optional sensors then HA will be able to track them for the user. 

According to HA discussions, it is no longer good practice to include states within attributes. I think it should just be configuration options.

Some examples: current temperature, target temperature, is heating, is boosted, is overridden...

**Comment by msp1974** [comment]
Kallum,

current temperature and target temperature are standard climate device attributes (standard as in defined by HA not this integration).

Depending on the size of your Wiser setup, this can be quite a big integration with over 100 entities.  As such, we are very concious of not creating everything as an individual entity but provide lots of attributes to allow those who do what some of them as specific sensor entities to create template entities from them.  Equally, many of the attributes provided are designed to be used in automations and not just display.

If there is a specific list you have in mind and use cases, I would suggest maybe bringing this up on the forum and with enough interest, we could look to add these extra sensors in a future release(s).

**Comment by Kallb123** [comment]
My use cases would be things like: highlighting on a floorplan whether an area is heated, (or boosted), recording the temperatures and humidity for longer term, see how long is left on a boost on the dashboard.

If I want to see and track these values at the moment, I think I have to go into yaml and create template sensors for them. I have to consider what the device class is and various other things that are irrelevant to the user.

Some of the Home Assistant team discussed this issue recently here: https://github.com/home-assistant/architecture/discussions/821

I believe an appropriate summary would be: values that are measured and changing should not be attributes, they should be sensors (or binary_sensors or whatever). Attributes should be used for configuration values (maybe like hvac_modes and preset_modes). It is expected that there will be a lot of entities, but these can be organised into devices or disabled if the user doesn't want them.

**Comment by msp1974** [comment]
The main reason not to create all these attributes as sensors is that the integration already creates a lot of sensors and each sensor adds to the mem usage and storage requirements.  For example, my setup with 1 roomstat, 9 trvs and 2 plugs (by far not the biggest setup) creates over 120 entities.  If we add more for climate, why should we not do the same for other entity types, thus creating hundreds.

Agreed that for some users this means creating some template sensors for their specific use cases (which is why we provide so much additional data as attributes to give the most flexibility without over burden for all).

For the use cases you describe, it is very simple to achieve as attributes without creating template sensors (for floorplan - use state_attr on the item or dashboard - use entity card where you can select attribute) - agree if you want to track history or they are already sensors like current temp, humidity etc (you may need to enable LTS sensor option in config if on version prior to 3.3.1).

**Comment by andyblac** [comment]
could Flow Temp and Return Temp be added so the heating history graph would show these figure, this would be verry helpfull in my case.

when you hover over on the graph, this popup I mean.
<img width="267" alt="Screenshot 2023-03-31 at 08 50 52" src="https://user-images.githubusercontent.com/77936/229059987-56d35f75-1e81-4ae8-b0e6-83b9dddfd957.png">

**Comment by msp1974** [comment]
@Kallb123 does this answer your issue?

**Comment by Kallb123** [comment]
Sorry, yes, I completely missed the LTS option. I enabled that and now I have access to pretty much everything I'd like!
