### ISSUE TITLE
Climate Temperature does not show on area cards

### ISSUE THREAD

**Issue by 8run0** [asantaga/wiserHomeAssistantPlatform#381]
The climate sensor and the underlying temperature are both configured for the appropriate area but do not display on the area cards as per other temperature sensors set for specific areas.

**Comment by msp1974** [comment]
This will be fixed in the next release but will maybe cause some confussion on an area card.  As there is a current temp and a target temp sensor, the area card will show the average of these.  You will need to set the visible flag on the target temp sensor to off to exclude it from the area card.

I presume this is ok?

**Comment by msp1974** [comment]
Fixed in v3.3.10.
