### ISSUE TITLE
Error in switch.py, self.awayTemperature in update()

### ISSUE THREAD

**Issue by Langybangy** [asantaga/wiserHomeAssistantPlatform#39]
Hey, love this component, thanks :) however this has been bugging me for a couple of months or so; I see errors when setting away mode via HA with the switch, and then the component will freeze and not respond or update or anything until HA is restarted. 

I saw a couple of related issues that have opened and closed last few weeks / months, but my error persists with latest 1.7 update (using HACS). Very helpfully I don't have a note of the exact error but it is something like 'setAwayHome temperature can only be between 5 and 30 or -20 (Off)'.

I had a look around (I am familiar with code, but to be honest never used github properly as a contributor, so I will just point out the bits here, sorry) and found that switch.py update method, line 44/45 should read:

```
        self.awayTemperature = self.handler.get_hub_data().getSystem(). \
            get('AwayModeSetPointLimit')/10
```

rather than the current 

```
        self.awayTemperature = self.handler.get_hub_data().getSystem(). \
            get('AwayModeSetPointLimit')
```

to match line 36/37 in 'init' method.

Without this, it was trying to send an away mode setpoint with the raw api value of 140 (14 deg c) instead of 14, and this was failing the bounds checking (5-30 or -20) in wiserHub.py.

I'm not sure how this switch error would cause the whole component (including climate components etc) to freeze up, but I will keep an eye on it next few days.

Ta, Joe

**Comment by asantaga** [comment]
Hey joe

Thanks for the comments. Ah yes I agree and see the error, to be honest I thought I’d nabbed them all but this one through. I’ll mirror the changes in master tomorrow and at the same time go hunting for more changes.....

**Comment by asantaga** [comment]
No idea why this would freeze up HA thought......

**Comment by duncanbarnes** [comment]
Echo comments by Joe, also love this component! :-)

This is the complete error that Joe mentioned when setting away mode, but looks like he has identified the bug:

`
Log Details (ERROR)
Thu Dec 26 2019 17:20:16 GMT+0000 (Greenwich Mean Time)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 190, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 273, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 355, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 97, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 205, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 336, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 358, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wiser/switch.py", line 64, in turn_on
    self.handler.set_away_mode(True, self.awayTemperature)
  File "/config/custom_components/wiser/__init__.py", line 167, in set_away_mode
    self.wiserHubInstance.setHomeAwayMode(mode, away_temperature)
  File "/usr/local/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py", line 237, in setHomeAwayMode
    raise Exception("setAwayHome temperature can only be between 5 and 30 or -20(Off)")
Exception: setAwayHome temperature can only be between 5 and 30 or -20(Off)
`

In my experience at the moment it doesn't freeze HA, but it does stop any further actions in the same chain. So if used for an automation it has to be the last action otherwise anything after it wouldn't be executed because of the exception.

**Comment by Langybangy** [comment]
Just to clarify - the whole of HA doesn’t freeze, just this wiser integration / components, until HA is restarted. So for example, the temperatures won’t update anymore for rooms, etc, they just freeze at their current values.

**Comment by asantaga** [comment]
guys, sorry was ill with child donated lurgy .. bug fixed (thanks Joe) and Ive tested it on my home installation..

Im just checking some other things before making a new release

**Comment by asantaga** [comment]
Looks good, I pressed every button, looked at every dial.. seams to be ok
made release 1.7.1 so you HACS allows an upgrade
