### ISSUE TITLE
A new sensor feature. 

### ISSUE THREAD

**Issue by ialexyi** [asantaga/wiserHomeAssistantPlatform#406]
Could you please add a status sensor that indicates whether the device currently has been triggered on or off.
Thanks.

**Comment by msp1974** [comment]
Closing as no response to request for info.

**Comment by ialexyi** [comment]
Why did you close the ticket?
How many devices to you have that mostly used by the integration and can be triggered on and off?
It is easy to close the ticket rather than providing a code change, isn't it?

**Comment by msp1974** [comment]
Because the question is ambiguous and a request for more information received no response.

If you want some functionality then you have 2 options.

1. Code it yourself and provide a PR
2. Answer my questions so I understand what exactly you are asking for.

In the absence of either, showing no effort on your part, I will not put any of my time into it.  That is why the ticket was closed.
