### ISSUE TITLE
No opentherm data

### ISSUE THREAD

**Issue by jacekowski** [asantaga/wiserHomeAssistantPlatform#489]
I'm using hub v2 
CCTFR6311G2
Firmware: 4.34.53

It looks like opentherm data has gone missing few months ago (GET /data/v2/opentherm/ returns 404). Is that a hub v2 only issue? Is there a different endpoint on v2? Seems to have stopped working when firmware was updated to 4.32.47

**Comment by msp1974** [comment]
I don't have a v2 hub but it still shows on this path on a v1 hub.  Are you able to see what the Wiser app path is using?

**Comment by jacekowski** [comment]
Hi,

Correct URL now is /data/v2/openTherm/

**Comment by sol3uk** [comment]
Hi, 
I've also been wondering about the OpenTherm data that could be exposed via this integration? I initially setup my HubR using the standard mode, since plugging in the OpenTherm connections and enabling it in the Wiser app, I can't see any additional information via this integration in HA. Is this expected or are there any plans to bring this into the integration? 
Sorry if this is in the wrong place, I couldn't find any reference to OpenTherm in your documentation.

**Comment by jacekowski** [comment]
Opentherm data (if available) is exposed via hub entity attributes.

**Comment by jacekowski** [comment]
No, hub modulates the boiler based on temperatures

**Comment by msp1974** [comment]
Sorry for the delay, but this should now be resolved in 3.4.9 - just released.
